<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllDesc()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }

    public function deleteLast($count)
    {
        $qb = $this->createQueryBuilder('m');
        $query = $qb->select('m')
            ->orderBy('m.id', 'DESC')
            ->setMaxResults($count)
            ->getQuery();

        $res = $query->getResult();
        $em = $this->getEntityManager();

        foreach ($res as $message) {
            $em->remove($message);
        }

        $em->flush();

        return $res;
    }
    
}
