# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.messages_manager:
        class: AppBundle\Messages\MessagesManager
        arguments: ['@doctrine.orm.entity_manager','@fos_user.util.token_generator']
    app.registering:
        class: AppBundle\EventListener\RegistrationListener
        arguments: ['@doctrine.orm.entity_manager','@router']
        tags:
            - { name: kernel.event_subscriber }
